# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  job1:

    runs-on: ubuntu-latest
    concurrency:
      group: my-group

    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
              
    - name: Install dependencies
      run: poetry install --no-root

    - name: Cache build venv
      id: cache-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/<path>/example-app/.venv
        key: ${{ runner.os }}-venv

  job2:
    needs: job1
    runs-on: ubuntu-latest
    concurrency:
      group: my-group

    steps:
    
    - name: Lint 
      run: poetry run task lint

    - name: Formater
      run: poetry run task formatter

    - name: Security
      run: poetry run task security

    - name: Cache build venv
      id: cache-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/<path>/example-app/.venv
        key: ${{ runner.os }}-venv

  job3:
    
    needs: [job1, job2]
    runs-on: ubuntu-latest
    concurrency:
      group: my-group

    steps:
    
    - name: Test with pytest
      run: poetry run task test

    - name: Cache build venv
      id: cache-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: /home/runner/work/<path>/example-app/.venv
        key: ${{ runner.os }}-venv
